### PR TITLE
Create Product Page

### PR DESCRIPTION
**Pull request by saurabhchirde**

### CODE REVIEW

**Comment by sushmita12345** [comment]
Suggest to use 'px' if size is less than 1rem.
Looks nice! Good to merge.

**Review by sushmita12345 — APPROVED** [review]

**Review by m26unkwn — APPROVED** [review]
This Code is looking to me.

**Review by aiman-ansari — APPROVED** [review]
Everything looks good just a suggestion that you can remove cart label from navbar . Only cart icon will look good there. 
Also in share if you remove share icon then it might look good.

**Comment by saurabhchirde** [comment]
@aiman-ansari, Those features (cart label and share icon) are designed and used for a wide range of audiences.

**Pull request merged**
